name: trigger AWS jenkins job
on: [push]
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: TriggerAWSJenkinsJob
        run: curl -X POST ${{ secrets.NAVER_JENKINS_URL }}/job/${{ secrets.NAVER_JENKINS_JOB }}/build?token=${{ secrets.NAVER_JENKINS_JOB_TOKEN }} --user ${{ secrets.NAVER_JENKINS_USER }}:${{ secrets.NAVER_JENKINS_API_TOKEN }}
        timeout-minutes: 1
